@base_url = http://localhost:8000/api
@access_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5IiwiZXhwIjoxNzY3MjQ5MjMwLCJpYXQiOjE3NjY2NDQ0MzB9.QBr0wes6taOHx3flmiYRNLziUXWR1JleBM3eA8rBWC4
### create new mission
# @prompt mission_name Mission Name
# @prompt description Mission Description
POST {{base_url}}/missions/create
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
    "name": "{{mission_name}}",
    "description":"{{description}}"
}


### update mission
# @prompt mission_id Mission ID
# @prompt mission_name Mission Name
# @prompt description Mission Description
PATCH {{base_url}}/missions/{{mission_id}}/edit
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
    "name": "{{mission_name}}",
    "description": "{{description}}"
}


### remove mission
# @prompt mission_id Mission ID
DELETE {{base_url}}/missions/{{mission_id}}/remove
Content-Type: application/json
Authorization: Bearer {{access_token}}





### set mission to in-progress
# @prompt mission_id Mission ID to Set In-Progress
PATCH  {{base_url}}/mission/in-progress/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### set mission to completed
# @prompt mission_id Mission ID to Set Completed
PATCH  {{base_url}}/mission/to-completed/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### set mission to failed
# @prompt mission_id Mission ID to Set Failed
PATCH  {{base_url}}/mission/to-failed/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
